"""Create subscribers table

Revision ID: 783b6ecfabcd
Revises: 232041758755
Create Date: 2024-07-31 00:59:06.996383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783b6ecfabcd'
down_revision = '232041758755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('date_subscribed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscribed')
        batch_op.drop_column('show_newsletter_prompt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_newsletter_prompt', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('subscribed', sa.BOOLEAN(), nullable=False))

    op.drop_table('subscriber')
    # ### end Alembic commands ###
