"""Create subscribers table

Revision ID: c8053239fe17
Revises: 783b6ecfabcd
Create Date: 2024-07-31 11:31:03.217836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8053239fe17'
down_revision = '783b6ecfabcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriber')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscribed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('show_newsletter_prompt', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('show_newsletter_prompt')
        batch_op.drop_column('subscribed')

    op.create_table('subscriber',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('date_subscribed', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
