"""Initial migration

Revision ID: cb13dd7ac514
Revises: 
Create Date: 2024-08-12 14:16:40.820277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb13dd7ac514'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.alter_column('vitals',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.alter_column('vitals',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
