"""empty message

Revision ID: f9cc87a5ff4d
Revises: 7bec067b4e34
Create Date: 2024-08-28 23:29:37.716172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cc87a5ff4d'
down_revision = '7bec067b4e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.drop_column('stock_quantity')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_quantity', sa.INTEGER(), nullable=False))
        batch_op.drop_column('quantity')
        batch_op.drop_column('cost')
        batch_op.drop_column('tax')

    # ### end Alembic commands ###
